---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCQEghSebOb7V10fSt9JkX5Bchsc6EvXAkv90QQm/EgRbZ2o5eimE/jWhr9BBRuZDQ1NEh1bK6Tv/2aRu/18ErtirIu9Tz4ZOEGHO1dcXliMVCZY8Kwvf1BxxXUWvzxLuTi8o3nrNzMzjRJAYnNRt27aAOnXqCBh9b0WsJwD2xtC9t/9XaoO8LqVyk+CasGqCE6szlnA6w1f/1URUWPIn8nKoPHiEKHqzOURpwigoEk4Y1midS+pPX306zSwfJllAbHyIW+FtckKK01aFSDhP5D4bgici8FC9ty9AaJEArZg3uIRh//N0jQZ2RHpNml1LBrlibQw7f2sf4mrIbzVB7NswkSl1Y5QeB/jsMD2NIEj0rE9ZojUnYpYLkmisWKnW9blnGBxRDoAUsIlIuT2Z9lCosf4bB+dpcrbd13Gk035YKiBrR9cdyZNAQnj46j+/8x8GY2bI7sizMp8l+Sy84i91wAvevavL8pkSnJRT6i7KyiOhRVznv/8CtUKc2tf4f2Xzxyo27zLFyzS+hUMs8RBiJ8ve9BMtMjwQ/lZfioHQI1J8aGghjQckFiKl+GHsAsWlrnd9iM677Dv+FvEBrmHPvSigJ/Chyz1j/oVblypjq2XWarYaQt1F5LPM9E8iVWEm/EnI9hpXhWPIjc8qHf5fOu6l9M19Lc6HI8ihPX77dGPYyEqBkd25YtGFWhCU2guV8t1Fzuy3U4wbxa4HG73w==
    client_secret: AgB6LVdVcIauUFadmQIZBWFd3+gwIsy/oBSZMubB7Go/aTLevHGkk054x7fqHDQRZYOI44y8vEL0H4EjBW8T3iASn50OaKPCMlfXnlHe5/BLPKtDPM5O1DSTp4FETE5RFzh2AdX8GU8WZhrND01DvPCDKGeNEUoJ+L8/LqpDuUHm7X80fhbhbuelehl15zid3n/jpAAi4LX+REduuL7K69yn29H0OlTdYeifxV37qpinboLH0r3vzwZRXIVnIbW50H/wnRRjaf2qI1dcEBsHpyomWcTql9Gs5Hpm2Q9C0+8Fdi8WIbTfkna4x0wZHIfI336f7U75tI4xvFmEnMRp7myODXNev2CXNY2SE9mbGLhUyc8ct9ZyZaUHTfVjO2+6OprthNvwYgAJfrQndPGS4G3IjCubH/bQlBqI1itwqNBaPBNdJFwGUKy/Pb55EEiNJcEKYsnZfwgjzT7GjhtucTNsz91s1nqd/eEEk2Vr82Oy7YZjoFzEomMxTNAW5ew2927gJe6AeLYjth3deTVaQBNg6VPO9+bI7s85VQUqAqAHaDGVNssOJKZqfyo+AFVbtRf3ENwHceKrd4RP2HmaeK58nmTtYYc5qIE5dYDfVyN9OyYyLPEnE33BReaINbkt6G2IwBBN1G/5F40UtNl2pS1nJiE60g9gRzPsT9xwwWgMmxZ6MGoo5j8sknfXvp3rppcFRs2QHIGuPM12icdP5vlguhnEAW9O9EgzJoJh+2FgzNOZmgcZ2cyRgS19zX15d5gLxAQb1fOCM4xa21hQMl8K
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
    type: Opaque
