---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openwebui-credentials
  namespace: llm
spec:
  encryptedData:
    WEBUI_SECRET_KEY: AgAWKSdGCuFQRgxxvmtkdOREROgOoj8CWUk3s6ZSHZ4TScQXJlYy+2F0NLZ9XE/Qsw2oN0My+MsmVYcn6tiXE/X8vHjfXsEXtck3ibnEC6ROds+UHksRXHVOOYpl+4KmEIftUhLdkXT9tAXFFGje3KgdCg9lMD2uoQJhl6VL2cF1zzC3xCDd8OI7msXLW7kuQ8ZJwX6acrIY3lapH7l6mv/NSO9PSDomHrV5EYgONfhj+Wj5Z0iFWuOHzZQ1kP4U4IJRLFOc3UWgyVP+W1wUUjhtT+7rNDviGBxXXPDmfQ8LbJ65Q1v8n3kU2Soy89mlyaxgQPRaNuMnXb+bY/kWSfjZNrUXsJXJMaicCHu9+rYS8QglkWRTX75MsD1lkf3pjf53gcBvl9/9QLOp5V7c4BhRJWVecwTJqzfk5wH9Gf3xhp5b9iLaMjOp9sAD7dBj4mtC8/A6N3doh7cjMTq5p9IVcJ7yqdIHTZY942tGy7UUiqZcu9MONAHYjNBruHcwNzkP6lPRdF12/GCrDxr/agRtpBYYozn1GfNrG3wNeEQ7LVNahbQSjT5dmiFii6EuFHOigpcbmKsVghyzSWTxMzHG3Cca1DPV0GFEB2glbhVq3qIoUUpDk7Pim8hSNIClTh50V6MjlfKjcjov6yVqasCkfCh1qJF2YES/hAoZE8WNbmAt1CM0LgF82ZYLqzO8aDpA0viAIWb7kl/OAKgt4kxPOR6PrsOvSAiA90luOLS/GKHnKkVF4N6cnqzMikbH3ZChoGLNaxT7NAx23CFQcmWL
  template:
    metadata:
      name: openwebui-credentials
      namespace: llm
    type: Opaque
