apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openwebui
  namespace: llm
spec:
  rules:
  - host: openwebui.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openwebui
            port:
              number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ollama
  namespace: llm
spec:
  rules:
  - host: ollama.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ollama
            port:
              number: 11434