---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yml
  - 01-sealed-secret.yml
  - 02-pvc.yml
  - 03-deployment.yml
  - 04-service.yml
  - 05-ingress.yml