apiVersion: v1
kind: Service
metadata:
  name: cups
  namespace: default
  labels:
    app: cups
spec:
  selector:
    app: cups
  ports:
  - name: ipp
    port: 631
    targetPort: 631
    protocol: TCP
  type: ClusterIP
