---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgBQLY4AOVMSMp8b7foqqFZAoBAKL5fUD3QfIWTBd4QZl2SPnHSVjrRNIpj4/p/RvX8/VflHgxGhvIWEYOrSyRlUF+5sqO6D8QwqeMahsJxZAgJFlPgsWYTEAGmlxApPX6tkVa7EDWVspnzNE1VeGaKIaEOgM01jX/d4gGKhFZrZ1be7daxmXLnXcPUeWLV+7u7UwadUrGK49ZpuAX6XMS3ouiKWOUjGD1srRJ/E+j4vqOnXRMpd4lVtuuW3iuiJEi+C6T+13uAueqGUuXbXolTVG9iQPaOmHHyvbSoLKRBf0uSTACOmo/Fj5k85a6kwpl8MUpDAbDen0UGJANjdsCadJvwRg9yoILCZNV9HW4IgpC4eeolZNM5JUSryv6/AQjWqOs3sPV4kBpjj4lMEpPsaO6gh15RCQxCJU1WBdZkYcB7gD2WjnR/6zHDY0al0gStzb4eJBW9SJTXcU+qulIMUspgiF0F4HBMHaUJlOuUxfOhLad/rkvPPoxk47R4NFSAruugyFE8Mft5dd/gkRv1Utg70aV/8hrNhWKiDOzwJAyBzs1F3XJO2eRMlwxw1LgUR7L2Gh9adY9cVYRGaYIpcaqT7YdWYdChYjw9hBJ9FiwNQ6EahPL+UzjPjwyKIsbDUCObIlUedRAvEQJbT3qGEwh3h1dnWUp79/7JMpFp99EkvFJaDCM724CwdDT8T48xl/aPkXgkGbGBtI1tPf7tCM3Q2aUZgDjIm8XB12O+DKQw4AqlKsmZhfn4Ex0eI6l/1O7cobqnsBoOVW4K5qLk/EoZrJ2yd9kKeG8JDt1OXbws+dglFg1f+ihA8soAdwh7g1RMxmfUDgjoNojX1+DHJGgHdWtmCpDeKrj6cvW1XABTsMSw1MLhidmuGku7a+jtorLVI1r1DFm6EzAO5aN5PK/U2t9VG+58=
  template:
    metadata:
      name: tunnel-credentials
      namespace: cloudflared
    type: Opaque
