---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-immich-db
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-retain
  volumeName: immich-db

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-immich-photos
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: nfs-retain
  volumeName: immich-photos-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs-local-lvm

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailscale-state-claim
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs-local-lvm