
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-config
  namespace: immich
data:
  serve-config.json: |
    {
      "TCP": {"443": {"HTTPS": true}},
      "Web": {"${TS_CERT_DOMAIN}:443": {"Handlers": {"/": {"Proxy": "http://127.0.0.1:2283"}}}}
    }