---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-services
  namespace: immich
  labels:
    app: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: immich
    spec:
      containers:
        - name: immich-postgres
          image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
          env:
            - name: POSTGRES_INITDB_ARGS
              value: --data-checksums
            - name: DB_STORAGE_TYPE
              value: HDD
            - name: POSTGRES_DB
              value: immich
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: immich-credentials
                  key: db-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-credentials
                  key: db-password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: immich-database-storage

        - name: immich-server
          image: ghcr.io/immich-app/immich-server:v2
          env:
            - name: TZ
              value: America/Sao_Paulo
            - name: DB_HOSTNAME
              value: localhost
            - name: REDIS_HOSTNAME
              value: localhost
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: immich-credentials
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-credentials
                  key: db-password
          ports:
            - containerPort: 2283
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: immich-server-storage

        - name: immich-redis
          image: docker.io/valkey/valkey:9@sha256:3b55fbaa0cd93cf0d9d961f405e4dfcc70efe325e2d84da207a0a8e6d8fde4f9
          livenessProbe:
            exec:
              command:
                - redis-cli ping || exit 1

        - name: tailscale
          image: ghcr.io/tailscale/tailscale:latest
          env:
            - name: TS_HOSTNAME
              value: immich
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: immich-credentials
                  key: TS_AUTHKEY
            - name: TS_SERVE_CONFIG
              value: /etc/tailscale/serve-config.json
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: TS_STATE_DIR
              value: /var/lib/tailscale
          volumeMounts:
            - name: tailscale-state
              mountPath: /var/lib/tailscale
            - name: tailscale-config
              mountPath: /etc/tailscale

      volumes:
        - name: tailscale-config
          configMap:
            name: tailscale-config
        - name: tailscale-state
          persistentVolumeClaim:
            claimName: tailscale-state-claim
        - name: immich-server-storage
          persistentVolumeClaim:
            claimName: pvc-immich-photos
        - name: immich-database-storage
          persistentVolumeClaim:
            claimName: pvc-immich-db

      serviceAccountName: immich

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
  namespace: immich
  labels:
    app: immich-machine-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-machine-learning
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: immich-machine-learning
    spec:
      nodeSelector:
        nvidia.com/gpu.present: "true"
      containers:
        - name: immich-machine-learning
          image: ghcr.io/immich-app/immich-machine-learning:v2
          volumeMounts:
            - mountPath: /cache
              name: model-cache
      restartPolicy: Always
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: model-cache
